In [1]:
import pandas as pd
import numpy as np
amazon = pd.read_csv("amazon.csv")
amazon

,Name,Author,User Rating,Reviews,Price,Price_r,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,$8.00,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,$22.00,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,$15.00,15,2018,Non Fiction
3,1984,George Orwell,4.7,70425,$7.48,8,2021,Fiction
4,1984 (Signet Classics),George Orwell,4.7,21424,$6.00,6,2017,Fiction
...,...,...,...,...,...,...,...,...
645,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,$8.00,8,2019,Fiction
646,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2016,Non Fiction
647,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2017,Non Fiction
648,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2018,Non Fiction
649,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2019,Non Fiction

In [7]:
amazon_group = amazon.groupby(['Year', 'Genre'], as_index = False).agg({"User Rating":["mean"]})
amazon_group

    Year        Genre User Rating
                             mean
0   2009      Fiction    4.591667
1   2009  Non Fiction    4.576923
2   2010      Fiction    4.615000
3   2010  Non Fiction    4.520000
4   2011      Fiction    4.619048
5   2011  Non Fiction    4.513793
6   2012      Fiction    4.495238
7   2012  Non Fiction    4.558621
8   2013      Fiction    4.545833
9   2013  Non Fiction    4.561538
10  2014      Fiction    4.631034
11  2014  Non Fiction    4.609524
12  2015      Fiction    4.652941
13  2015  Non Fiction    4.645455
14  2016      Fiction    4.715789
15  2016  Non Fiction    4.654839
16  2017      Fiction    4.737500
17  2017  Non Fiction    4.588462
18  2018      Fiction    4.738095
19  2018  Non Fiction    4.617241
20  2019      Fiction    4.820000
21  2019  Non Fiction    4.686667
22  2020      Fiction    4.713043
23  2020  Non Fiction    4.737037
24  2021      Fiction    4.716667
25  2021  Non Fiction    4.746154